# Setup
title:               Hildegard
tagline:             '1877 bibliography on the life and works of Hildegard of Bingen (1098-1179)'
description:         'site description'
url:                 
baseurl:             '/cgeroux'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Author name
  url:               author url
  email:             author email

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y



collections:
  sections:
    output: true
  monographical:
    output: false
  historical-biographical:
    output: false

